### ISSUE TITLE
port to plasma 6

### ISSUE THREAD

**Issue by cruzki** [alex1701c/EmojiRunner#13]
Would this krunner be ported to plasma6? This is the only thing I am missing at this point from plasma 5 at this moment.

**Comment by alex1701c** [comment]
I will try to get it done next weekend!

**Comment by cruzki** [comment]
Awesome!

**Comment by alex1701c** [comment]
Can you try on master?

**Comment by cruzki** [comment]
Seem like there is a problem with the install script. It is looking to KF5. 

./install.sh: línea 13: kf5-config: command not found
-- Could not set up the appstream test. appstreamcli is missing.
-- Could NOT find KF5I18n (missing: KF5I18n_DIR)
-- Could NOT find KF5I18n: found neither KF5I18nConfig.cmake nor kf5i18n-config.cmake 
-- Could NOT find KF5Runner (missing: KF5Runner_DIR)
-- Could NOT find KF5Runner: found neither KF5RunnerConfig.cmake nor kf5runner-config.cmake 
-- Could NOT find KF5ConfigWidgets (missing: KF5ConfigWidgets_DIR)
-- Could NOT find KF5ConfigWidgets: found neither KF5ConfigWidgetsConfig.cmake nor kf5configwidgets-config.cmake 
-- Could NOT find KF5KCMUtils (missing: KF5KCMUtils_DIR)
-- Could NOT find KF5KCMUtils: found neither KF5KCMUtilsConfig.cmake nor kf5kcmutils-config.cmake 
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find KF5 (missing: I18n Runner ConfigWidgets KCMUtils) (Required
  is at least version "5.105.0")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/ECM/find-modules/FindKF5.cmake:93 (find_package_handle_standard_args)
  CMakeLists.txt:23 (find_package)

**Comment by alex1701c** [comment]
The -DBUILD_WITH_QT6=ON part is missing in the cmake arguments. I am not sure how to best handle this for the KDE store :thinking:

**Comment by cruzki** [comment]
OK, I have change 

#cmake -DCMAKE_BUILD_TYPE=Release -DKDE_INSTALL_QTPLUGINDIR=$(kf5-config --qt-plugins)  ..

to

cmake -DCMAKE_BUILD_TYPE=Release -DKDE_INSTALL_QTPLUGINDIR=$(/usr/lib64/qt6/bin/qtpaths6 --qt-query QT_INSTALL_PLUGINS) -DBUILD_WITH_QT6=ON ..

and now I can star compiling but I have the following error:

[...]
En el fichero incluido desde /home/cruzki/EmojiRunner/build/src/emojirunner_autogen/JGCWW4IXAT/moc_emojirunner.cpp:9,
                 desde /home/cruzki/EmojiRunner/build/src/emojirunner_autogen/mocs_compilation.cpp:2:
/home/cruzki/EmojiRunner/build/src/emojirunner_autogen/JGCWW4IXAT/../../../../src/runner/emojirunner.h:39:10: error: declaration of ‘xdo* EmojiRunner::xdo’ changes meaning of ‘xdo’ [-Wchanges-meaning]
   39 |     xdo *xdo;
      |          ^~~
/home/cruzki/EmojiRunner/build/src/emojirunner_autogen/JGCWW4IXAT/../../../../src/runner/emojirunner.h:39:5: nota: used here to mean ‘struct xdo’
   39 |     xdo *xdo;
      |     ^~~
/home/cruzki/EmojiRunner/build/src/emojirunner_autogen/JGCWW4IXAT/../../../../src/runner/emojirunner.h:15:8: nota: se declara aquí
   15 | struct xdo;
      |        ^~~
En el fichero incluido desde /home/cruzki/EmojiRunner/src/runner/emojirunner.cpp:1:
/home/cruzki/EmojiRunner/src/runner/emojirunner.h:39:10: error: declaration of ‘xdo* EmojiRunner::xdo’ changes meaning of ‘xdo’ [-Wchanges-meaning]
   39 |     xdo *xdo;
      |          ^~~
/home/cruzki/EmojiRunner/src/runner/emojirunner.h:39:5: nota: used here to mean ‘struct xdo’
   39 |     xdo *xdo;
      |     ^~~
/home/cruzki/EmojiRunner/src/runner/emojirunner.h:15:8: nota: se declara aquí
   15 | struct xdo;
      |        ^~~
make[2]: *** [src/CMakeFiles/emojirunner.dir/build.make:83: src/CMakeFiles/emojirunner.dir/emojirunner_autogen/mocs_compilation.cpp.o] Error 1
make[2]: *** Se espera a que terminen otras tareas....
[ 13%] Building CXX object src/CMakeFiles/kcm_krunner_emojirunner.dir/config/emojirunner_popup.cpp.o
/home/cruzki/EmojiRunner/src/runner/emojirunner.cpp: In constructor ‘EmojiRunner::EmojiRunner(QObject*, const KPluginMetaData&, const QVariantList&)’:
/home/cruzki/EmojiRunner/src/runner/emojirunner.cpp:23:102: aviso: parámetro ‘args’ sin uso [-Wunused-parameter]
   23 | EmojiRunner::EmojiRunner(QObject *parent, const KPluginMetaData &pluginMetaData, const QVariantList &args)
      |                                                                                  ~~~~~~~~~~~~~~~~~~~~^~~~
make[2]: *** [src/CMakeFiles/emojirunner.dir/build.make:97: src/CMakeFiles/emojirunner.dir/runner/emojirunner.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:186: src/CMakeFiles/emojirunner.dir/all] Error 2
make[1]: *** Se espera a que terminen otras tareas....
[ 13%] Linking CXX shared module ../bin/kcm_krunner_emojirunner.so
[ 13%] Built target kcm_krunner_emojirunner
make: *** [Makefile:166: all] Error 2

I have installed: 

cruzki@semiorka ~/EmojiRunner $ eix xdotool
[I] x11-misc/xdotool
     Available versions:  3.20211022.1

without xdotool installed, the error is different:

cruzki@semiorka ~/EmojiRunner/build $ make -j$(nproc)
[ 13%] Built target emojirunner_autogen_timestamp_deps
[ 13%] Built target kcm_krunner_emojirunner_autogen_timestamp_deps
[ 13%] Built target kcm_krunner_emojirunner_autogen
[ 13%] Built target emojirunner_autogen
[ 13%] Building CXX object src/CMakeFiles/emojirunner.dir/emojirunner_autogen/mocs_compilation.cpp.o
[ 13%] Building CXX object src/CMakeFiles/emojirunner.dir/runner/emojirunner.cpp.o
[ 13%] Building CXX object src/CMakeFiles/emojirunner.dir/core/Emoji.cpp.o
[ 13%] Building CXX object src/CMakeFiles/emojirunner.dir/core/FileReader.cpp.o
[ 13%] Building CXX object src/CMakeFiles/kcm_krunner_emojirunner.dir/kcm_krunner_emojirunner_autogen/mocs_compilation.cpp.o
[ 13%] Building CXX object src/CMakeFiles/kcm_krunner_emojirunner.dir/config/emojirunner_config.cpp.o
[ 13%] Building CXX object src/CMakeFiles/kcm_krunner_emojirunner.dir/core/Emoji.cpp.o
[ 13%] Building CXX object src/CMakeFiles/kcm_krunner_emojirunner.dir/core/FileReader.cpp.o
[ 13%] Building CXX object src/CMakeFiles/kcm_krunner_emojirunner.dir/config/emojirunner_popup.cpp.o
/home/cruzki/EmojiRunner/src/runner/emojirunner.cpp: In constructor ‘EmojiRunner::EmojiRunner(QObject*, const KPluginMetaData&, const QVariantList&)’:
/home/cruzki/EmojiRunner/src/runner/emojirunner.cpp:23:102: aviso: parámetro ‘args’ sin uso [-Wunused-parameter]
   23 | EmojiRunner::EmojiRunner(QObject *parent, const KPluginMetaData &pluginMetaData, const QVariantList &args)
      |                                                                                  ~~~~~~~~~~~~~~~~~~~~^~~~
/home/cruzki/EmojiRunner/src/runner/emojirunner.cpp: In member function ‘void EmojiRunner::emitCTRLV()’:
/home/cruzki/EmojiRunner/src/runner/emojirunner.cpp:163:5: error: ‘QProcess’ no se ha declarado
  163 |     QProcess::startDetached("xdotool", QStringList{"key", "ctrl+v"});
      |     ^~~~~~~~
make[2]: *** [src/CMakeFiles/emojirunner.dir/build.make:97: src/CMakeFiles/emojirunner.dir/runner/emojirunner.cpp.o] Error 1
make[2]: *** Se espera a que terminen otras tareas....
make[1]: *** [CMakeFiles/Makefile2:186: src/CMakeFiles/emojirunner.dir/all] Error 2
make[1]: *** Se espera a que terminen otras tareas....
[ 13%] Linking CXX shared module ../bin/kcm_krunner_emojirunner.so
[ 13%] Built target kcm_krunner_emojirunner
make: *** [Makefile:166: all] Error 2
cruzki@semiorka ~/EmojiRunner/build $

**Comment by alex1701c** [comment]
Please check if master works fine for you now!

**Comment by cruzki** [comment]
👍🎉🥳

copied and pasted from krunner!!

**Comment by alex1701c** [comment]
Great, I will make a release then!

**Comment by mercifulboss** [comment]
> Great, I will make a release then!

Hello, it doesn't seem to compile from the install script in the discover store for krunner in KDE6

Also, can you please add an uninstall script?

**Comment by alex1701c** [comment]
>Hello, it doesn't seem to compile from the install script in the discover store for krunner in KDE6

Oh, I haven't updated it there. 

> Also, can you please add an uninstall script? 

Okay dokey :)
