### ISSUE TITLE
AUR

### ISSUE THREAD

**Issue by veger** [alex1701c/EmojiRunner#16]
Hi,

I tried using the PKGBUILD from the repo and it is severely outdated. I managed to upgrade (for Plasma 6) and it worked. Kind of, the emojis did not show in Krunner, instead there were only empty rectangles (missing glyph symbol I suppose). When I install from KDE store, the emojis are showing (no idea what is different).

Also the link to AUR (in the README) is broken.

I am willing to
* create a new (plasma6 build in AUR), but I might need some help fixing the font issue, and PKGBUILD from this repo (needs to) get removed (as it will live in AUR repo).
* fix PKGBUILD in this repo (Although it is a little awkward as it downloads a binary and starts build in the (existing) src folder of the repo)
* make a PR to just remove PKGBUILD and the reference to AUR.
* do nothing

Let me know what your preference would be 😉 (emoji copied from Krunner!)

**Comment by alex1701c** [comment]
Heyho, thanks for reaching out. TBH I am not experienced in regard to the AUR and don't have the setup/capacity to get into it.

What you are willing to do sounds great! I don't know about the font issue - is this a general one in KDE?
