### ISSUE TITLE
No color emoji after install

### ISSUE THREAD

**Issue by benjamindaines** [alex1701c/EmojiRunner#19]
As title states, not getting color emojis.  Color emojis work fine elsewhere (such as KDE emoji picker app).  Ran the fc-cache command linked to in the description, did not work.  

Exact solution should be posted on description page, not a discussion thread which the user has to figure out on their own.

Ideally non-color emoji condition should be automatically fixed during install and not something users have to deal with at all.  

Please list an exact fix and mitigate issue going forward.

**Comment by benjamindaines** [comment]
Manjaro is the distro, noto-color-emoji font is installed

**Comment by benjamindaines** [comment]
Perhaps an option to select the emoji font of choice would be the best way to fix this problem.  clearly whatever config it's pulling from is incorrect and KDE doesn't seem to provide a way to select the emoji font.

**Comment by benjamindaines** [comment]
Following the instructions posted near the end of the discussion (the reddit link) broke all my fonts and I needed to revert via the pacnew file stored in /etc/fonts/

This is why the color emoji fix needs to be part of the installation process.  I'm not going to mess with it anymore, it's just going to be broken until a specific fix is provided.

**Comment by alex1701c** [comment]
Hmm, I fear I can not help out with the distro/KDE Font management :(
