### ISSUE TITLE
show more emoji's

### ISSUE THREAD

**Issue by jospoortvliet** [alex1701c/EmojiRunner#3]
Hi,

I guess this is a krunner issue - but I often only see 1 or 2 results from the emoji krunner, the rest is from the desktop search. When I disable the file search, all is fine so I guess krunner limits the emoji runner in how much it can show? Do you know if this is configurable or if there's a way to see the full results?

**Comment by alex1701c** [comment]
Hey,
have you tried https://raw.githubusercontent.com/alex1701c/Screenshots/master/EmojiRunner/search_with_prefix.png ?

The issue generally is that there are a lot of results from many different plugins, that is why I implemented the prefix `emoji`.

**Comment by jospoortvliet** [comment]
oooh, I really didn't understand you can do that!  Does the trick!
