### ISSUE TITLE
Maximum number of favourites

### ISSUE THREAD

**Issue by fabianski7** [alex1701c/EmojiRunner#4]
Are there any limitations for this?

I have defined 14 and they do not display completely when I type `emoji`; only the first five.

**Comment by alex1701c** [comment]
I think you might have results from other runners too, is that correct?

I fear this is a regression on the KDE side from https://invent.kde.org/plasma/milou/-/commit/841c044894a609bb2215959f0273c47597841ffd. Could you please file a bug on https://bugs.kde.org/enter_bug.cgi?product=krunner? I will try to have a look in this week.

**Comment by fabianski7** [comment]
> I think you might have results from other runners too, is that correct?

Yes. When I type `emoji`, three results are displayed: the KDE emoji picker, a file in ~/Downloads and this plugin.
If only one is disabled, leaving only two in the results, the number of emojis displayed increases to 7.
And if all the others are deactivated, all the emojis are displayed

I made a test by creating a few text files with the same name and a folder in the same way, the same behavior happens. 

From what I understand this is intentional and is done to prevent results from taking up the whole screen. Would it still be necessary to open the bug?

**Comment by alex1701c** [comment]
Previously it always displayed up to 20 results, so I would consider it a bug ;)

**Comment by fabianski7** [comment]
Done https://bugs.kde.org/show_bug.cgi?id=433085

**Comment by alex1701c** [comment]
The number of results for KRunner has been reduced to 15. Thus this issue is no longer a real problem
