### ISSUE TITLE
No emoji avaolable

### ISSUE THREAD

**Issue by Shitdroid** [alex1701c/EmojiRunner#7]
There is no emojis shown in the krunner or in configurations
![image](https://user-images.githubusercontent.com/77888617/212248286-def509a2-a64a-4386-8e07-6160412248b0.png)

**Comment by alex1701c** [comment]
How have you installed the plugin and on which distro are you?

In case you build it yourself, please attach the install_manifest.txt from the build directory.

**Comment by alex1701c** [comment]
Please reopen if you can provide the requested info. Thanks :)
