### ISSUE TITLE
Install failed.

### ISSUE THREAD

**Issue by Base-115** [alex1701c/EmojiRunner#8]
Hi there.

I tried to install your plugin from "Discover" app in Kubuntu and the Terminal showed "incomplete install".

I am basically a noob in Linux Desktop, but I guess the stuff that I am sending can help to solve the problem, if this extension is maintain, yet, what would be cool.

___

Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.19.0-50-generic (64-bit)

___

Copy of verbose install(?) 
[EmojiRunnerLogFail.txt](https://github.com/alex1701c/EmojiRunner/files/12167085/EmojiRunnerLogFail.txt)

Log fail install
[CMakeOutput.log](https://github.com/alex1701c/EmojiRunner/files/12167095/CMakeOutput.log)

**Comment by alex1701c** [comment]
Try installing the libkf5textwidgets-dev package

**Comment by Base-115** [comment]
So cool, I install the package and reinstall the plugin and now it's working.

Thank you. ❤️

Another thing: I found some bug in System Settings, but I do not know if you maintain the plugin yet, although you helped me now, 😅.

**Comment by Base-115** [comment]
Anyway, I created bug report about this issue commented in the previous message here:  https://github.com/alex1701c/EmojiRunner/issues/9#issue-1828041334 .

Since the issue for that session was solved, I closed this bug report.

**Comment by alex1701c** [comment]
>but I do not know if you maintain the plugin yet, although you helped me now, sweat_smile.

The plugin is in my GitHub namespace and that usually means I am the maintainer :D Or one could use the good old rule: Who last touched the code is now the maintainer ^^
