### ISSUE TITLE
Bug: plugin settings panel settings in "System Settings disappear and back.

### ISSUE THREAD

**Issue by Base-115** [alex1701c/EmojiRunner#9]
SUMMARY

Plugin settings panel in "System Settings" always show completely odd when open for the second time.

STEP TO REPRODUCE
1. Open "System Settings";
2. Go to Search > Plasma Search;
3. Locate "EmojiRunner" and click to the button to panel settings;
4. Close the window or click on "OK" button or "Cancel" button;
5. Open the plugin settings panel again;

___

Video showing the issue.

https://github.com/alex1701c/EmojiRunner/assets/112908515/899140c3-9a69-40de-9861-7f9ffd158b13

___

My Linux Distro installed

Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.19.0-50-generic (64-bit)
Graphics Platform: X11

**Comment by alex1701c** [comment]
Yeah, that is due to a weird KCM bug that I did a workaround for. I'll look into it
